USE test;

CREATE TABLE Author (
  IDAuthor BIGINT AUTO_INCREMENT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Surname VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDAuthor)
);

CREATE TABLE Books (
  IDBooks BIGINT AUTO_INCREMENT NOT NULL,
  Name VARCHAR(200) NOT NULL,
  ISBN CHAR(13) NOT NULL,
  Quantity INT NOT NULL,
  AuthorID BIGINT NOT NULL,
  PRIMARY KEY (IDBooks),
  FOREIGN KEY (AuthorID) REFERENCES Author(IDAuthor) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Customer (
  IDCustomer BIGINT AUTO_INCREMENT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Surname VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDCustomer)
);

CREATE TABLE BookLoan (
  IDBookLoan BIGINT AUTO_INCREMENT NOT NULL,
  IDCustomer BIGINT NOT NULL,
  IDBooks BIGINT NOT NULL,
  IsActive BIT NOT NULL,
  Date DATETIME NOT NULL,
  PRIMARY KEY (IDBookLoan),
  FOREIGN KEY (IDBooks) REFERENCES Books(IDBooks) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (IDCustomer) REFERENCES Customer(IDCustomer) ON UPDATE CASCADE ON DELETE CASCADE
);
